### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/stewart/Dropbox'

### ISSUE THREAD

**Issue by stewartbryson** [thedaniel/terminal-panel#39] opened 2015-03-06 20:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.9.2

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/stewart/Dropbox'

```
At fs.js:807

Error: ENOENT, no such file or directory '/Users/stewart/Dropbox'
    at Error (native)
    at fs.statSync (fs.js:807:18)
    at Object.fs.statSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:155:14)
    at CommandOutputView.module.exports.CommandOutputView._fileInfoHtml (/Users/stewart/.atom/packages/terminal-panel/lib/command-output-view.coffee:283:19)
    at /Users/stewart/.atom/packages/terminal-panel/lib/command-output-view.coffee:255:41
    at Array.forEach (native)
    at CommandOutputView.module.exports.CommandOutputView.ls (/Users/stewart/.atom/packages/terminal-panel/lib/command-output-view.coffee:253:13)
    at space-pen-div.<anonymous> (/Users/stewart/.atom/packages/terminal-panel/lib/command-output-view.coffee:122:26)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)
```

### Commands

```
     -1:28.7 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-one-light-ui)
 28x -0:58.9 core:move-down (atom-text-editor.editor)
 17x -0:56.1 core:move-up (atom-text-editor.editor)
     -0:54.5 core:move-left (atom-text-editor.editor)
     -0:54.0 editor:newline (atom-text-editor.editor)
 11x -0:49.4 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-gradle, v0.0.3
language-groovy, v0.3.0
terminal-panel, v1.9.2

# Dev
No dev packages
```

**Comment by braver** [comment] 2015-05-06 20:17
duplicate of #36

**Closed by braver** 2015-05-06 20:17 UTC
